<a href="https://colab.research.google.com/github/Sunkara-saivardhan/Machine-Learning-Based-Airline-Passenger-Satisfaction-Prediction-Using-KNN-DT-RF-FastAPI/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#keras
#tensorflow

In [ ]:
#import required libraries
import keras #library of neural networks
import pandas as pd #loading data in table form
import seaborn as sns #visulization
import matplotlib.pyplot as plt #visulization
import numpy as np #mathematical operations
from sklearn.preprocessing import normalize #machine learning algorithm library
from sklearn.model_selection import train_test_split

In [ ]:
#loading the data
data= pd.read_csv("/content/iris.csv")
data.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
data.shape

(150, 5)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [ ]:
data.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
print(data.head(10)) #first 10 samples of the dataset
print(data.tail(10)) #"last 10 samples of the dataset

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa
     sepal_length  sepal_width  petal_length  petal_width    species
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [ ]:
data['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
data.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [ ]:
data.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
data.loc[data['species']=='setosa','species']=0
data.loc[data['species']=='versicolor','species']=1
data.loc[data['species']=='virginica','species']=2
print(data.head())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2       0
1           4.9          3.0           1.4          0.2       0
2           4.7          3.2           1.3          0.2       0
3           4.6          3.1           1.5          0.2       0
4           5.0          3.6           1.4          0.2       0

In [ ]:
#shiffling data because our data has 150 rows in that first 50 species are  setosa and next 50 versicolor and last 50 are virginica is not good to train the model
data=data.loc[np.random.permutation(len(data))]
data.head()

     sepal_length  sepal_width  petal_length  petal_width species
26            5.0          3.4           1.6          0.4       0
14            5.8          4.0           1.2          0.2       0
24            4.8          3.4           1.9          0.2       0
138           6.0          3.0           4.8          1.8       2
75            6.6          3.0           4.4          1.4       1

In [ ]:
x=data.drop(columns=['species'])
y=data['species']
print(x.shape)
print(y.shape)

(150, 4)
(150,)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)

(120, 4)
(30, 4)

In [ ]:
y_train

20     0
17     0
72     1
50     1
83     1
      ..
118    2
78     1
8      0
126    2
149    2
Name: species, Length: 120, dtype: object

In [ ]:
#neural network modules
from keras.models import Sequential
from keras.layers import Dense, Activation
#from keras.utilts import np_utilts
import tensorflow as tf

In [ ]:
#change label to one hot encoder
'''
[0]->[1,0,0]
[1]->[0,1,0]
[2]->[0,0,1]
'''
y_train=tf.keras.utils.to_categorical(y_train,num_classes=3)
y_test=tf.keras.utils.to_categorical(y_test,num_classes=3)
print("shape of y_train",y_train.shape)
print("shape of y_test",y_test.shape)

shape of y_train (120, 3)
shape of y_test (30, 3)

In [ ]:
#multi-class classfication
#define keras model

model=Sequential()

model.add(Dense(32, input_dim=4, activation='relu'))# 1 hidden layers and input_dim represent how many neurons in input layer
model.add(Dense(64,  activation='relu'))# 2 hidden layer
model.add(Dense(128, activation='relu'))# 3 hidden layer

model.add(Dense(3, activation='softmax'))# output layer

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.compile(
    loss='categorical_crossentropy', #error
    optimizer='adam', #gradient decent
    metrics=['accuracy'] #accuracy
)

In [ ]:
#training the data
model.fit(X_train,y_train,
    validation_data=(X_test, y_test),
    batch_size=30,
    epochs=30)

Epoch 1/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 5s 313ms/step - accuracy: 0.3750 - loss: 1.1544 - val_accuracy: 0.6000 - val_loss: 1.0204
Epoch 2/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.4917 - loss: 0.9934 - val_accuracy: 0.4000 - val_loss: 0.9406
Epoch 3/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 88ms/step - accuracy: 0.3917 - loss: 0.9692 - val_accuracy: 0.7000 - val_loss: 0.8854
Epoch 4/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.6500 - loss: 0.8867 - val_accuracy: 0.7000 - val_loss: 0.8374
Epoch 5/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.7667 - loss: 0.8215 - val_accuracy: 0.6000 - val_loss: 0.8030
Epoch 6/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.6833 - loss: 0.7754 - val_accuracy: 0.6000 - val_loss: 0.7421
Epoch 7/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.7917 - loss: 0.7095 - val_accuracy: 0.9667 - val_loss: 0.6663
Epoch 8/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.8667 - loss: 0.6487 - val_accuracy: 0.7000 - val_loss: 0.6065
Epoch 9/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6667 - loss: 0.6019 - val_accuracy: 0.7000 - val_loss: 0.5603
Epoch 10/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.6750 - loss: 0.5585 - val_accuracy: 0.7000 - val_loss: 0.5213
Epoch 11/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.8083 - loss: 0.5156 - val_accuracy: 0.9333 - val_loss: 0.4951
Epoch 12/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.9333 - loss: 0.4883 - val_accuracy: 1.0000 - val_loss: 0.4714
Epoch 13/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.9500 - loss: 0.4528 - val_accuracy: 0.9333 - val_loss: 0.4362
Epoch 14/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9583 - loss: 0.4272 - val_accuracy: 0.9333 - val_loss: 0.4110
Epoch 15/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9667 - loss: 0.4056 - val_accuracy: 0.9333 - val_loss: 0.3887
Epoch 16/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9333 - loss: 0.3846 - val_accuracy: 0.9333 - val_loss: 0.3649
Epoch 17/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9583 - loss: 0.3599 - val_accuracy: 1.0000 - val_loss: 0.3457
Epoch 18/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9500 - loss: 0.3411 - val_accuracy: 1.0000 - val_loss: 0.3337
Epoch 19/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.9417 - loss: 0.3202 - val_accuracy: 1.0000 - val_loss: 0.3030
Epoch 20/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.9750 - loss: 0.3011 - val_accuracy: 0.9333 - val_loss: 0.2836
Epoch 21/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9583 - loss: 0.2863 - val_accuracy: 1.0000 - val_loss: 0.2654
Epoch 22/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9667 - loss: 0.2681 - val_accuracy: 1.0000 - val_loss: 0.2455
Epoch 23/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.9667 - loss: 0.2547 - val_accuracy: 0.9333 - val_loss: 0.2276
Epoch 24/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.9750 - loss: 0.2353 - val_accuracy: 1.0000 - val_loss: 0.2119
Epoch 25/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9667 - loss: 0.2206 - val_accuracy: 1.0000 - val_loss: 0.1938
Epoch 26/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9750 - loss: 0.2071 - val_accuracy: 1.0000 - val_loss: 0.1765
Epoch 27/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9500 - loss: 0.2044 - val_accuracy: 1.0000 - val_loss: 0.1647
Epoch 28/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9667 - loss: 0.1827 - val_accuracy: 0.9333 - val_loss: 0.1575
Epoch 29/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9750 - loss: 0.1756 - val_accuracy: 1.0000 - val_loss: 0.1396
Epoch 30/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9333 - loss: 0.1777 - val_accuracy: 1.0000 - val_loss: 0.1292

In [ ]:
y_pred = model.predict(X_test)
print("accuracy",y_pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step
accuracy [[1.03525110e-02 8.76467168e-01 1.13180377e-01]
 [9.96606112e-01 3.39307496e-03 8.23839116e-07]
 [9.91785765e-01 8.20933096e-03 4.80415338e-06]
 [1.58265830e-05 5.59043698e-02 9.44079757e-01]
 [6.61738543e-03 9.42225456e-01 5.11572286e-02]
 [8.05372911e-05 1.38176322e-01 8.61743152e-01]
 [1.74747838e-03 6.09860420e-01 3.88392091e-01]
 [9.96111989e-01 3.88670107e-03 1.25636177e-06]
 [1.07490203e-04 1.24049284e-01 8.75843287e-01]
 [2.62485337e-05 7.23018795e-02 9.27671790e-01]
 [8.36279336e-03 8.84765327e-01 1.06871895e-01]
 [9.93120670e-01 6.87440392e-03 4.81378675e-06]
 [2.84256414e-03 8.16443026e-01 1.80714414e-01]
 [5.55182560e-05 6.84827790e-02 9.31461692e-01]
 [1.01376500e-03 6.21690214e-01 3.77295911e-01]
 [9.93771732e-01 6.22587232e-03 2.34248228e-06]
 [4.53459477e-04 1.86320871e-01 8.13225627e-01]
 [1.20649002e-02 9.21323478e-01 6.66116104e-02]
 [3.74200754e-03 8.40099394e-01 1.56158656e-01]
 [9.95272577e-01 4.72559035e-03 1.92215361e-06]
 [9.91847456e-01 8.14428553e-03 8.16572265e-06]
 [9.36708238e-05 2.89384931e-01 7.10521400e-01]
 [9.96997058e-01 3.00207897e-03 8.19148113e-07]
 [7.43005876e-05 1.53560296e-01 8.46365392e-01]
 [1.15958690e-04 1.46337748e-01 8.53546321e-01]
 [5.84523613e-03 8.55804443e-01 1.38350308e-01]
 [9.94343162e-01 5.65436902e-03 2.50889661e-06]
 [1.63729317e-04 2.55836725e-01 7.43999600e-01]
 [1.95358716e-05 7.42494985e-02 9.25730944e-01]
 [8.60752116e-05 1.76679060e-01 8.23234797e-01]]